# Generated by Django 5.0.6 on 2024-07-20 11:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('state', models.CharField(choices=[('START_SOON', 'START_SOON'), ('GOING_ON', 'GOING_ON'), ('ENDED', 'ENDED')], default='START_SOON', max_length=128)),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tournament',
                'verbose_name_plural': 'Tournaments',
            },
        ),
        migrations.CreateModel(
            name='RoundsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_rounds', to='tournament.tournamentmodel')),
            ],
            options={
                'verbose_name': 'Round',
                'verbose_name_plural': 'Rounds',
            },
        ),
        migrations.CreateModel(
            name='MatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rounds', models.CharField(blank=True, max_length=50, null=True)),
                ('result', models.SmallIntegerField(blank=True, null=True)),
                ('data_for_ondelete', models.JSONField(blank=True, null=True)),
                ('side_black', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_black', to=settings.AUTH_USER_MODEL)),
                ('side_white', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='side_white', to=settings.AUTH_USER_MODEL)),
                ('which_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_rounds', to='tournament.roundsmodel')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_rounds', to='tournament.tournamentmodel')),
            ],
            options={
                'verbose_name': 'Match',
                'verbose_name_plural': 'Matches',
            },
        ),
    ]
