# Generated by Django 5.0.6 on 2024-07-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundsmodel',
            name='round_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='roundsmodel',
            name='data_for_ondelete',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
