# Generated by Django 5.0.6 on 2024-07-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_roundsmodel_round_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roundsmodel',
            old_name='round_id',
            new_name='rounds',
        ),
    ]
