# Generated by Django 5.0.6 on 2024-07-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_rename_round_id_roundsmodel_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentmodel',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
